# Generated by Django 5.2.3 on 2025-06-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_users_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
